# Generated by Django 5.2.7 on 2025-10-24 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='campus',
            field=models.ForeignKey(blank=True, db_column='campus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_account',
            field=models.OneToOneField(db_column='user_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='commitment_status',
            field=models.CharField(choices=[('not_committed', 'Not Committed'), ('committed', 'Committed'), ('completed', 'Completed')], db_column='commitment_status', default='not_committed', help_text='Student commitment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='target_score',
            field=models.IntegerField(blank=True, db_column='target_score', help_text='Target IELTS/TOEIC score', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_account',
            field=models.OneToOneField(db_column='user_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(blank=True, db_column='campus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.TextField(blank=True, db_column='level', help_text='Teacher level (e.g., Junior, Senior, Expert)', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.TextField(blank=True, db_column='specialization', help_text='Teacher specialization (e.g., IELTS Speaking, TOEIC)', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_account',
            field=models.OneToOneField(db_column='user_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['campus'], name='managers_campus__b45a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['user_account'], name='managers_user_ac_9df757_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['commitment_status'], name='students_commitm_096f31_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user_account'], name='students_user_ac_a950b3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['campus'], name='teachers_campus__b65c73_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user_account'], name='teachers_user_ac_2bbda5_idx'),
        ),
    ]
