# Generated by Django 5.2.7 on 2025-10-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_manager_campus_alter_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='commitment_status',
            field=models.CharField(choices=[('not_committed', 'Not Committed'), ('committed', 'Committed'), ('canceled', 'Canceled')], db_column='commitment_status', default='not_committed', help_text='Student commitment status', max_length=20),
        ),
    ]
