# Generated by Django 5.2.7 on 2025-10-09 15:51

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_student_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('course_id', models.UUIDField()),
                ('weekday', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None)),
                ('time_slot', models.TextField(blank=True, null=True)),
                ('teacher_id', models.UUIDField(blank=True, null=True)),
                ('campus_id', models.UUIDField(blank=True, null=True)),
                ('manager_id', models.UUIDField(blank=True, null=True)),
                ('limit_slot', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
    ]
