# Generated by Django 5.2.7 on 2025-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
