"""
Django settings for english_center project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Đảm bảo python-decouple tìm được .env file
# Tìm .env file từ BASE_DIR (thư mục chứa manage.py)
env_path = BASE_DIR / '.env'
if env_path.exists():
    # Sử dụng Config với RepositoryEnv để chỉ định đường dẫn cụ thể
    env_config = Config(RepositoryEnv(str(env_path)))
    # Override config function để sử dụng env_config
    def get_config(key, default=None):
        return env_config(key, default=default)
    config = get_config
else:
    # Fallback về config mặc định nếu không tìm thấy .env
    pass  # config đã được import từ decouple

# Google Cloud Vision API
# Ưu tiên: 1. Environment variable, 2. File trong folder credentials
GOOGLE_VISION_CREDENTIALS_PATH = config(
    'GOOGLE_VISION_CREDENTIALS_PATH',
    default=None
)

# Nếu không có trong env, tự động tìm trong folder credentials (cách 1)
if not GOOGLE_VISION_CREDENTIALS_PATH:
    default_credentials_path = BASE_DIR / 'proficiency' / 'credentials' / 'google_vision_credentials.json'
    if default_credentials_path.exists():
        GOOGLE_VISION_CREDENTIALS_PATH = str(default_credentials_path)

# VNPay Configuration
VNPAY_TMN_CODE = config('VNPAY_TMN_CODE', default='')
VNPAY_HASH_SECRET = config('VNPAY_HASH_SECRET', default='')
VNPAY_URL = config('VNPAY_URL', default='https://sandbox.vnpayment.vn/paymentv2/vpcpay.html')
VNPAY_RETURN_URL = config('VNPAY_RETURN_URL', default='http://localhost:8000/api/enrollment/payments/vnpay/return/')
VNPAY_IPN_URL = config('VNPAY_IPN_URL', default='http://localhost:8000/api/enrollment/payments/vnpay/notify/')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4zawvf^8h#)53h_f0^01c88kn(p@&f5#aoyekh_bz8rdhq8h+5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    
    # Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    
    # Third party apps
    'corsheaders',
    'django_filters',
    'drf_yasg',
    
    # Local apps
    'core',
    'authentication',
    'campus',
    'users',
    'courses',
    'assignments',

    'classes',
    'enrollment',
    'class_sessions',
    'requests',
    'tests',
    'proficiency',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'english_center.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'english_center.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# settings.py
DATABASES = {
    'default': {

        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'english_center_db_utf8',
        'USER': 'postgres',
        'PASSWORD': 'Maily@1407',  # Password bạn đã đặt
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'authentication.UserAccount'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # ← Phải có
]
# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'core.renderers.CustomJSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.CustomPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKEN': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Configuration - Cho phép frontend gọi API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5500",      # Live Server (VSCode)
    "http://127.0.0.1:5500",
    "http://localhost:8080",      #EDB PostgreSQL:
    "http://127.0.0.1:8080",
    "http://localhost:9000",      # Python HTTP Server (port thay thế)
    "http://127.0.0.1:9000",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Spectacular (Swagger) Configuration
# SPECTACULAR_SETTINGS = {
#     'TITLE': 'English Center API',
#     'DESCRIPTION': 'API documentation for English Center Management System',
#     'VERSION': '1.0.0',
#     'SERVE_INCLUDE_SCHEMA': False,
#     'SCHEMA_PATH_PREFIX': '/api/v1/',
# }

# Email Configuration (for password reset)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Google OAuth Configuration
GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_OAUTH2_CLIENT_ID', default=None)
GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default=None)

# Frontend URLs (optional)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5500')
FRONTEND_LOGIN_PAGE = config('FRONTEND_LOGIN_PAGE', default='/login.html')