# Generated by Django 5.2.7 on 2025-10-09 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('session_id', models.UUIDField()),
            ],
            options={
                'db_table': 'assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=16)),
                ('student_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
            ],
            options={
                'db_table': 'attendances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('skill_id', models.UUIDField(blank=True, null=True)),
                ('class_id', models.UUIDField()),
                ('room_id', models.UUIDField(blank=True, null=True)),
                ('teacher_id', models.UUIDField(blank=True, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField()),
                ('status', models.CharField(default='submitted', max_length=32)),
                ('content', models.TextField(blank=True, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment_id', models.UUIDField()),
                ('student_id', models.UUIDField()),
            ],
            options={
                'db_table': 'submissions',
                'managed': False,
            },
        ),
    ]
