# Generated by Django 5.2.7 on 2025-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'managed': False, 'ordering': ['study_date', 'start_time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
