# Generated by Django 5.2.7 on 2025-11-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_rename_phone_campus_description_campus_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='manager',
        ),
    ]
