# Generated by Django 5.2.7 on 2025-11-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_campus_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Số lượng thiết bị'),
        ),
    ]
