# Generated by Django 5.2.7 on 2025-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
