# Generated by Django 5.2.7 on 2025-10-09 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.UUIDField()),
                ('class_id', models.UUIDField()),
            ],
            options={
                'db_table': 'leave_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReserveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.UUIDField()),
                ('class_id', models.UUIDField()),
            ],
            options={
                'db_table': 'reserve_requests',
                'managed': False,
            },
        ),
    ]
