# Generated by Django 5.2.7 on 2025-10-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'managed': False},
        ),
    ]
