# Generated by Django 5.2.7 on 2025-12-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_add_teacher_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('skill_group', models.CharField(choices=[('LR', 'Listening-Reading'), ('SW', 'Speaking-Writing')], db_column='skill_group', help_text='LR: Listening-Reading; SW: Speaking-Writing', max_length=2)),
                ('source_type', models.CharField(choices=[('certificate', 'Chứng chỉ'), ('entry_test', 'Test đầu vào'), ('final_test', 'Test cuối khóa')], db_column='source_type', help_text='certificate: Chứng chỉ; entry_test: Test đầu vào; final_test: Test cuối khóa', max_length=20)),
                ('score_1', models.IntegerField(blank=True, db_column='score_1', help_text='Listening (nếu LR) hoặc Speaking (nếu SW)', null=True)),
                ('score_2', models.IntegerField(blank=True, db_column='score_2', help_text='Reading (nếu LR) hoặc Writing (nếu SW)', null=True)),
                ('total_score', models.IntegerField(db_column='total_score', help_text='Điểm tổng. LR: 0-990, SW: 0-400')),
                ('test_date', models.DateField(db_column='test_date', help_text='Ngày thi hoặc ngày làm bài')),
                ('expired_date', models.DateField(db_column='expired_date', help_text='Ngày hết hạn của kết quả')),
                ('proof_image', models.TextField(blank=True, db_column='proof_image', help_text='Link ảnh chứng chỉ', null=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Đã xác thực'), ('PENDING', 'Chờ duyệt'), ('REJECTED', 'Từ chối')], db_column='status', default='PENDING', help_text='VERIFIED: Đã xác thực; PENDING: Chờ duyệt; REJECTED: Từ chối', max_length=20)),
                ('verification_method', models.CharField(choices=[('auto_ocr', 'Tự động OCR'), ('manual_admin', 'Admin duyệt thủ công')], db_column='verification_method', default='auto_ocr', help_text='auto_ocr: Tự động xác thực bằng OCR; manual_admin: Admin duyệt thủ công', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', help_text='Admin thực hiện duyệt (null nếu hệ thống tự duyệt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'verbose_name_plural': 'Student Certificates',
                'db_table': 'student_certificates',
                'ordering': ['-test_date'],
                'indexes': [models.Index(fields=['student', 'skill_group'], name='student_cer_student_e6d146_idx'), models.Index(fields=['status'], name='student_cer_status_283d3d_idx'), models.Index(fields=['-test_date'], name='student_cer_test_da_ba1c7c_idx'), models.Index(fields=['expired_date'], name='student_cer_expired_30b45a_idx'), models.Index(fields=['student', 'skill_group', 'status', 'expired_date'], name='student_cer_student_69bd8e_idx')],
            },
        ),
    ]
