# Generated by Django 5.2.7 on 2025-10-11 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id', models.UUIDField()),
                ('question_id', models.UUIDField()),
                ('selected_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamInstanceQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_instance_id', models.UUIDField()),
                ('question_id', models.UUIDField()),
                ('order_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_instance_questions',
                'managed': False,
            },
        ),
    ]
